builder/bob-musl dockerfiles die on kubler-build-root failure

diff --git a/builder/bob-musl/Dockerfile.berney b/builder/bob-musl/Dockerfile.berney
--- a/builder/bob-musl/Dockerfile.berney
+++ b/builder/bob-musl/Dockerfile.berney
@@ -2,8 +2,8 @@
 # The syntax line needs to be the first line
 
 # There's two very similar Dockerfiles:
-#   - Dockerfile.builder
-#   - Dockerfile.berney
+#   - Dockerfile.builder - has /distfiles and /packages
+#   - Dockerfile.berney - clean, no /distfiles, no /packages
 #
 # The difference is berney one will produce an image without `/distifiles/` nor `/packages/` directories,
 # because it's `RUN` had `--mount` with `type=cache`.
@@ -37,12 +37,17 @@ COPY --link build.sh /config/
 #RUN --mount=type=cache,target=/distfiles,from=distfiles --mount=type=cache,target=/packages,from=packages <<-EOF
 RUN --mount=type=cache,from=distfiles,target=/distfiles \
     --mount=type=cache,from=packages,target=/packages <<-EOF
+  die() {
+    exit_code="${2:-1}"
+    echo -e 'fatal:' "$1" >&2
+    exit "${exit_code}"
+  }
   env | grep -E '^((BOB|DEF)_|PKGDIR)'
   ls -lF /
   ls -lF /config
   ls -ltraF /distfiles | tail || true
   ls -ltraF /packages | tail || true
-  BOB_CURRENT_TARGET=berney/bob-musl kubler-build-root
+  BOB_CURRENT_TARGET=berney/bob-musl kubler-build-root || die "kubler-build-root failed"
   ls -ltraF /distfiles | tail || true
   ls -ltraF /packages | tail || true
 EOF
