Extract agent

diff --git a/.github/workflows/agent.yml b/.github/workflows/agent.yml
--- a/.github/workflows/agent.yml
+++ b/.github/workflows/agent.yml
@@ -21,19 +21,29 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Docker Run Hello-World
-        run: |
-          docker pull alpine
-          docker run --rm alpine date
-          docker run --rm hello-world
-
       - name: Docker pull agent
         run: |
-          docker pull ghcr.io/berney/aether-tunnel/agent:main || echo "Failed to pull image"
+          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"
+
+      - name: Extract Agent
+        run: |
+          docker create --name agent ghcr.io/berney/aether-tunnel/agent
+          pwd
+          mkdir etc
+          docker cp agent:/etc/s6_finish_default etc/
+          docker cp agent:/etc/service/ etc/
+          docker cp agent:/service/ .
+          docker cp agent:/usr/bin/ .
+          docker cp agent:/usr/local/bin/ .
+          touch service/web-shell/down
+          touch service/nginx/down
+          export PATH="$(pwd)/bin:$PATH"
+          s6-svscan service &
 
       - name: docker run agent
+        if: false
         run: |
-          docker run -d --name agent ghcr.io/berney/aether-tunnel/agent:main || echo "Failed to run image"
+          docker run -d --name agent ghcr.io/berney/aether-tunnel/agent || echo "Failed to run image"
 
       - name: Inspect
         run: |
@@ -48,6 +58,7 @@ jobs:
           sleep 60m
 
       - name: Stop Agent
+        if: false
         run: |
           docker stop agent
           docker rm agent
