Run agent earlier to troubleshoot login

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -16,6 +16,56 @@ jobs:
     name: Azure
     runs-on: ubuntu-latest
     steps:
+      - name: 🐋 Docker Login
+        #if: ${{ false }}
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Docker pull agent
+        #if: ${{ false }}
+        run: |
+          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"
+
+      - name: Extract Agent
+        #if: ${{ false }}
+        env:
+          LIGOLO_PROXY: ${{ secrets.LIGOLO_PROXY }}
+        run: |
+          docker create --name agent ghcr.io/berney/aether-tunnel/agent
+          pwd
+          mkdir etc
+          docker cp agent:/etc/s6_finish_default etc/
+          docker cp agent:/etc/service/ etc/
+          docker cp agent:/service/ .
+          docker cp agent:/usr/bin/ .
+          docker cp agent:/usr/local/bin/ .
+          docker rm agent
+          touch service/web-shell/down
+          touch service/nginx/down
+          export PATH="$(pwd)/bin:$PATH"
+          mkdir ~/log
+          s6-svscan service &
+
+      - name: Inspect
+        if: ${{ false }}
+        run: |
+          set -eux
+          sleep 10
+          ps -ef
+          pstree
+          docker ps
+          docker ps -a
+          ss -nlt
+          ss -nlu
+          ip link
+          ip addr
+          ip -6 addr
+          ls -l ~/log/mosh-server/current || true
+          cat ~/log/mosh-server/current || true
+
       - name: Azure login
         uses: azure/login@v2
         with:
@@ -52,54 +102,6 @@ jobs:
             az storage container list --account-name berneygithub || true
             az storage container-rm list --storage-account berneygithub || true
             az storage blob list --account-name berneygithub --container-name packages --auth-mode login --output table
-
-      - name: 🐋 Docker Login
-        if: ${{ false }}
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Docker pull agent
-        if: ${{ false }}
-        run: |
-          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"
-
-      - name: Extract Agent
-        if: ${{ false }}
-        run: |
-          docker create --name agent ghcr.io/berney/aether-tunnel/agent
-          pwd
-          mkdir etc
-          docker cp agent:/etc/s6_finish_default etc/
-          docker cp agent:/etc/service/ etc/
-          docker cp agent:/service/ .
-          docker cp agent:/usr/bin/ .
-          docker cp agent:/usr/local/bin/ .
-          docker rm agent
-          touch service/web-shell/down
-          touch service/nginx/down
-          export PATH="$(pwd)/bin:$PATH"
-          mkdir ~/log
-          s6-svscan service &
-
-      - name: Inspect
-        if: ${{ false }}
-        run: |
-          set -eux
-          sleep 10
-          ps -ef
-          pstree
-          docker ps
-          docker ps -a
-          ss -nlt
-          ss -nlu
-          ip link
-          ip addr
-          ip -6 addr
-          ls -l ~/log/mosh-server/current || true
-          cat ~/log/mosh-server/current || true
 
       - name: Blob FUSE
         #continue-on-error: true
@@ -164,7 +166,7 @@ jobs:
           fi
 
       - name: Sleep
-        if: ${{ false }}
+        #if: ${{ false }}
         run: |
           set -eux
           LOOPS=12
@@ -181,5 +183,7 @@ jobs:
             ip -6 addr
             ls -l ~/log/mosh-server/current || true
             cat ~/log/mosh-server/current || true
+            ls -l ~/log/ligolo-ng/current || true
+            cat ~/log/ligolo-ng/current || true
             sleep 5m
           done
