Extract agent in azure

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -35,13 +35,38 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Start Agent
+      - name: Docker pull agent
         run: |
-          docker pull alpine
-          docker run --rm alpine date
-          docker run --rm hello-world
-          docker pull ghcr.io/berney/aether-tunnel/agent:main || echo "Failed to pull image"
-          docker run -d --name agent ghcr.io/berney/aether-tunnel/agent:main || echo "Failed to run image"
+          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"
+
+      - name: Extract Agent
+        run: |
+          docker create --name agent ghcr.io/berney/aether-tunnel/agent
+          pwd
+          mkdir etc
+          docker cp agent:/etc/s6_finish_default etc/
+          docker cp agent:/etc/service/ etc/
+          docker cp agent:/service/ .
+          docker cp agent:/usr/bin/ .
+          docker cp agent:/usr/local/bin/ .
+          docker rm agent
+          touch service/web-shell/down
+          touch service/nginx/down
+          export PATH="$(pwd)/bin:$PATH"
+          s6-svscan service &
+
+      - name: Inspect
+        run: |
+          sleep 10
+          ps -ef
+          pstree
+          docker ps
+          docker ps -a
+          ss -nlt
+          ss -nlu
+          ip link
+          ip addr
+          ip -6 addr
 
       - name: Blob FUSE
         run: |
@@ -91,9 +116,17 @@ jobs:
 
       - name: Sleep
         run: |
-          sleep 60m
-
-      - name: Stop Agent
-        run: |
-          docker stop agent
-          docker rm agent
+          LOOPS=12
+          for x in $(seq $LOOPS); do
+            echo "== $x/$LOOPS"
+            ps -ef
+            pstree
+            docker ps
+            docker ps -a
+            ss -nlt
+            ss -nlu
+            ip link
+            ip addr
+            ip -6 addr
+            sleep 5m
+          done
