If dgoss testing fails, test again with `-l debug`
- This should make diagnosing why a testing failed easier.
- This way I get simple testing output if testing passes, but also get
  more details if testing fails, so I can probably work out what is
  wrong without pulling the image to investigate.
- Also the testing repeating means that if a test is flakey the second
  one might pass.

diff --git a/.github/workflows/builders.yml b/.github/workflows/builders.yml
--- a/.github/workflows/builders.yml
+++ b/.github/workflows/builders.yml
@@ -118,6 +118,7 @@ jobs:
       - name: 🐋🍳 Docker Bake Kubler stage3 - test pulled
         id: stage3-pull-test
         if: ${{ steps.stage3-pull.outcome == 'success' }}
+        # If the pulled image fails tests, a subsequent step will try baking
         continue-on-error: true
         run: |
           set -eux
@@ -128,6 +129,15 @@ jobs:
           docker run --rm "${{ matrix.stage3.image }}" ls -la /usr/bin/gcc /usr/sbin/gcc || true
           cd "${{ matrix.stage3.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "$KUBLER_IMAGE" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.stage3.image }}" validate --color
+
+      - name: 🐋🍳 Docker Bake Kubler stage3 - test pulled - debug
+        if: ${{ steps.stage3-pull-test.outcome == 'failure' }}
+        # If the pulled image fails tests, a subsequent step will try baking
+        continue-on-error: true
+        run: |
+          set -eux
+          cd "${{ matrix.stage3.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "$KUBLER_IMAGE" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.stage3.image }}" -l debug validate --color
 
       - name: 🐋🍳 Docker Bake Kubler stage3 - list targets
         if: ${{ steps.stage3-pull.outcome == 'failure' || steps.stage3-pull-test.outcome == 'failure' }}
@@ -156,7 +166,10 @@ jobs:
 
 
       - name: 🐋🍳 Docker Bake Kubler stage3 - test baked
+        id: stage3-bake-test
         if: ${{ steps.stage3-pull.outcome == 'failure' || steps.stage3-pull-test.outcome == 'failure' }}
+        # If this test fails, we will test again with `-l debug` to help troubleshooting, which should fail the job
+        continue-on-error: true
         run: |
           set -eux
           docker run --rm "${{ matrix.stage3.tmp_image }}" cat /etc/gentoo-release
@@ -166,6 +179,13 @@ jobs:
           docker run --rm "${{ matrix.stage3.tmp_image }}" ls -la /usr/bin/gcc /usr/sbin/gcc || true
           cd "${{ matrix.stage3.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "$KUBLER_IMAGE" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.stage3.tmp_image }}" validate --color
+
+      - name: 🐋🍳 Docker Bake Kubler stage3 - test baked - debug
+        if: ${{ steps.stage3-bake-test.outcome == 'failure' }}
+        run: |
+          set -eux
+          cd "${{ matrix.stage3.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "$KUBLER_IMAGE" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.stage3.tmp_image }}" -l debug validate --color
 
       - name: 🐋🍳 Docker Bake Kubler stage3 - oras cp
         if: ${{ steps.stage3-pull.outcome == 'failure' || steps.stage3-pull-test.outcome == 'failure' }}
@@ -190,6 +210,8 @@ jobs:
       - name: 🐋🍳 Docker Bake Kubler bob-core - test pulled
         id: bob-core-pull-test
         if: ${{ steps.bob-core-pull.outcome == 'success' }}
+        # If this fails we will test again with `-l debug` then fail
+        continue-on-error: true
         run: |
           set -eux
           docker run --rm "${{ matrix.core.image }}" cat /etc/gentoo-release
@@ -198,6 +220,13 @@ jobs:
           docker run --rm "${{ matrix.core.image }}" ls -l /var/cache
           cd "${{ matrix.core.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.core.image }}" validate --color
+
+      - name: 🐋🍳 Docker Bake Kubler bob-core - test pulled - debug
+        if: ${{ steps.bob-core-pull-test.outcome == 'failure' }}
+        run: |
+          set -eux
+          cd "${{ matrix.core.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.core.image }}" -l debug validate --color
 
       - name: 🐋🍳 Docker Bake Kubler bob-core - list targets
         if: ${{ steps.bob-core-pull.outcome == 'failure' || steps.bob-core-pull-test.outcome == 'failure' }}
@@ -221,7 +250,10 @@ jobs:
           #  core.cache-to=type=gha,scope=${{ matrix.core.cache }}
 
       - name: 🐋🍳 Docker Bake Kubler bob-core - test baked
+        id: bob-core-pull-test
         if: ${{ steps.bob-core-pull.outcome == 'failure' || steps.bob-core-pull-test.outcome == 'failure' }}
+        # If this fails we will test again with `-l debug`, and then fail
+        continue-on-error: true
         run: |
           set -eux
           docker run --rm "${{ matrix.core.tmp_image }}" cat /etc/gentoo-release
@@ -230,6 +262,13 @@ jobs:
           docker run --rm "${{ matrix.core.tmp_image }}" ls -l /var/cache
           cd "${{ matrix.core.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.core.tmp_image }}" validate --color
+
+      - name: 🐋🍳 Docker Bake Kubler bob-core - test baked - debug
+        if: ${{ steps.bob-core-pull-test.outcome == 'failure' }}
+        run: |
+          set -eux
+          cd "${{ matrix.core.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.core.tmp_image }}" -l debug validate --color
 
       - name: 🐋🍳 Docker Bake Kubler bob-core - oras cp
         if: ${{ steps.bob-core-pull.outcome == 'failure' || steps.bob-core-pull-test.outcome == 'failure' }}
@@ -253,6 +292,8 @@ jobs:
       - name: 🐋 Docker Build kubler builder - bob - test pulled
         id: bob-pull-test
         if: ${{ steps.bob-pull.outcome == 'success' }}
+        # if this fails we will test again with `-l debug` and then fail
+        continue-on-error: true
         run: |
           set -eux
           docker run --rm "${{ matrix.bob.image }}" cat /etc/gentoo-release
@@ -265,6 +306,13 @@ jobs:
           cd "${{ matrix.bob.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.image }}" validate --color
 
+      - name: 🐋 Docker Build kubler builder - bob - test pulled - debug
+        if: ${{ steps.bob-pull-test.outcome == 'failure' }}
+        run: |
+          set -eux
+          cd "${{ matrix.bob.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.image }}" -l debug validate --color
+
       - name: 🐋 Docker Build kubler builder - bob - test pulled - ripgrep
         # https://bugs.gentoo.org/922372 Bug 922372 - sys-apps/ripgrep-14.1.0 fails to compile (MUSL-SYSTEM): = note: ld: cannot find -lpcre2-8: No such file or directory
         id: bob-pull-test-ripgrep
@@ -275,6 +323,15 @@ jobs:
           docker run --rm "${{ matrix.bob.image }}" rg --version || true
           cd "${{ matrix.bob.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint -e GOSS_FILE=goss-ripgrep.yaml "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.image }}" validate --color
+
+      - name: 🐋 Docker Build kubler builder - bob - test pulled - ripgrep - debug
+        if: ${{ steps.bob-pull-test-ripgrep.outcome == 'failure' }}
+        # If ripgrep testing fails we keep going
+        continue-on-error: true
+        run: |
+          set -eux
+          cd "${{ matrix.bob.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint -e GOSS_FILE=goss-ripgrep.yaml "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.image }}" -l debug validate --color
 
       - name: 🐋 Docker Build kubler builder - bob - list targets
         if: ${{ steps.bob-pull.outcome == 'failure' || steps.bob-pull-test.outcome == 'failure' }}
@@ -298,7 +355,10 @@ jobs:
           #  ${{matrix.bob.target}}.cache-to=type=gha,scope=${{ matrix.bob.cache }}
 
       - name: 🐋 Docker Build kubler builder - bob - test baked
+        id: bob-bake-test
         if: ${{ steps.bob-pull.outcome == 'failure' || steps.bob-pull-test.outcome == 'failure' }}
+        # if this fails we will test again with `-l debug` and then fail
+        continue-on-error: true
         run: |
           set -eux
           docker run --rm "${{ matrix.bob.tmp_image }}" cat /etc/gentoo-release
@@ -311,7 +371,15 @@ jobs:
           cd "${{ matrix.bob.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.tmp_image }}" validate --color
 
+      - name: 🐋 Docker Build kubler builder - bob - test baked - debug
+        if: ${{ steps.bob-bake-test.outcome == 'failure' }}
+        run: |
+          set -eux
+          cd "${{ matrix.bob.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.tmp_image }}" -l debug validate --color
+
       - name: 🐋 Docker Build kubler builder - bob - test baked ripgrep
+        id: bob-bake-test-ripgrep
         if: ${{ steps.bob-pull.outcome == 'failure' || steps.bob-pull-test.outcome == 'failure' }}
         continue-on-error: true
         run: |
@@ -319,6 +387,15 @@ jobs:
           docker run --rm "${{ matrix.bob.tmp_image }}" rg --version || true
           cd "${{ matrix.bob.goss }}" || exit 1
           docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint -e GOSS_FILE=goss-ripgrep.yaml "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.tmp_image }}" validate --color
+
+      - name: 🐋 Docker Build kubler builder - bob - test baked ripgrep - debug
+        if: ${{ steps.bob-bake-test-ripgrep.outcome == 'failure' }}
+        # we keep going if ripgrep testing fails
+        continue-on-error: true
+        run: |
+          set -eux
+          cd "${{ matrix.bob.goss }}" || exit 1
+          docker run --rm -v /run/docker.sock:/run/docker.sock -v "$(pwd):/src:ro" -w /src -e CONTAINER_MODE=entrypoint -e GOSS_FILE=goss-ripgrep.yaml "${KUBLER_IMAGE}" dgoss run -w /goss --entrypoint /goss/goss "${{ matrix.bob.tmp_image }}" -l debug validate --color
 
       - name: 🐋🍳 Docker Bake Kubler builder - bob - oras cp
         if: ${{ steps.bob-pull.outcome == 'failure' || steps.bob-pull-test.outcome == 'failure' }}
